[zsh]
depends = ["os"]

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"
"zsh/.zshenv" = "~/.zshenv"

[zim]
depends = ["zsh"]

[zim.files]
"zim/config" = { target = "~/.zim", type = "symbolic" }
"zim/.zimrc" = { target = "~/.zimrc", type = "symbolic" }


[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"

[foot]
depends = ["os"]

[foot.files]
"foot/foot.ini" = "~/.config/foot/foot.ini"
"foot/theme/tokyonight" = "~/.local/share/foot/themes/tokyonight"

[foot.variables]
versionPre1_17 = false

[sway.files]
"sway/config" = "~/.config/sway/config"

[kickoff]
depends = ["sway"]

[kickoff.files]
"kickoff/config.toml" = "~/.config/kickoff/config.toml"

[waybar]
depends = ["sway"]

[waybar.files]
"waybar/config"  = "~/.config/waybar/config"
"waybar/style.css" = "~/.config/waybar/style.css"

[nvim.files]
"nvim/init.lua" = "~/.config/nvim/init.lua"
"nvim/lua/" = "~/.config/nvim/lua/"

[os.variables]
isArch = true
